### PR TITLE
faq.json: Finish translation to hindi

### PR DESCRIPTION
**Pull request by ashwini0529**

### CODE REVIEW

**Comment by hemangsk** [comment]
ack e26655b

**Comment by hemangsk** [comment]
@rultor merge

**Comment by ashwini0529** [comment]
@hemangsk are there any issues?😐

**Comment by hemangsk** [comment]
@ashwini0529 This is good to go, btw Hindi should be available in the https://github.com/coala/projects/blob/master/index.html#L58 dropdown as well so that users can are able to select it from dropdown to view the translation, do you mind adding it in the dropdown as well.

**Comment by gureks** [comment]
@ashwini0529 This needs rebasing

**Comment by ashwini0529** [comment]
@gureks Doing it in a while and updating my PR. 😄

**Comment by hemangsk** [comment]
@ashwini0529 Now we don't have to add new language in the markup dropdown, instead just add a json here https://github.com/coala/projects/blob/master/resources/js/app.js#L9

**Comment by ashwini0529** [comment]
Perfect @hemangsk

**Comment by ashwini0529** [comment]
@hemangsk added `Hindi` in the menu. Also rebased it. I think it's good to go?
Please let me know if anything else is required.

**Comment by hemangsk** [comment]
ack f7f45ea

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
