### PR TITLE
gitmate_gitlab.md Fix link, correct typos

### PR DESCRIPTION
**Pull request by Razoic**
Fix: broken link for Bitbucket, correct various typos

Fixes: https://github.com/coala/projects/issues/224

### CODE REVIEW

**Comment by sahilarora535** [comment]
The commit message and shortlog needs revision. Please go through [this](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) guide.

**Comment by Razoic** [comment]
I believe the errors in the commit message were resoled

**Comment by Sanny26** [comment]
@Razoic  The issue is to correct typos and broken link. Could I know why your PR has a description of the project? Seems like you have copied the file and created a new one..is it meant to be in the PR?

**Comment by Razoic** [comment]
I was attempting to replace the commit comments with the update. I was using Desktop Github, which I've since been advised not too. I am interested in trying to participate however the added complexity of trying to do so in a Windows environment via Bash on Ubuntu on Windows, added to my confusion. If you could please rollback this to its preassigned state (keeping the issue open) I'ld appreciate it.  I'm relearning the process on a Ubuntu vbox, and git management, and a smaller project, I hope to rejoin when able.

**Comment by Sanny26** [comment]
@Razoic  I'm a newcomer as well. I too took a lot of time to understand git and submit a PR without doing any errors. If you are talking about withdrawing from this issue, I think you should give it a try once again. 
I think you can use git reset to remove your last commit (not sure, though)
Use this link: https://api.coala.io/en/latest/Developers/Git_Basics.html .I find the link very helpful whenever I do a mistake.

**Comment by Razoic** [comment]
As I understand it, you are reviewing this PR, and not approving it. I do not understand your comment on what needs to changed. The only test it is failing is your review. Please revert this issue to it's previous state,

**Comment by Sanny26** [comment]
You have two commits on your PR. First one fixes the issue, and the second one adds a new file, right? All I'm asking is why do you have this file? It doesn't seem to be related to the issue.

**Comment by Razoic** [comment]
Please refer to the comments above. 
1. I made a pull request that contained the first commit to 'Razoic: raz-projects-2'. 
2. sahilarora535 reviewed my commit (review/gitmate/manual )
    - he advised me the commit comments were not in the correct style
3. following the instructions in the guide, I made a new commit to the branch ' Razoic: raz-projects-2'. with an updated commit message.
4. Sanny26 reviewed, This is the point in the process I no longer understand what is wrong with the pull request as is, I spend a number of hours researching why it would not pass review, failing to find a reason, I requested you rollback this issue to it's per-assignment status, as I am not certain of the process to do so without closing the issue.

**Comment by Sanny26** [comment]
Please look at https://github.com/coala/projects/pull/225/files
The first commit you did on your branch made the necessary changes required for the issue.
After sahilarora535 reviewed the commit, you were asked to make changes to your commit message. Along with the changes to the message, you have uploaded an additional file to the branch, which is not relevant to the issue. All I am asking for you is to remove this additional file.
Is this understandable?

**Pull request closed without merging**
