### PR TITLE
Add internationalised GitBook support

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/projects/issues/64

### CODE REVIEW

**Comment by jayvdb** [comment]
The build can be seen at https://www.gitbook.com/book/coala/projects/activity?branch=gitbook
Rendered version at https://coala.gitbooks.io/projects/content/v/gitbook/

**Comment by jayvdb** [comment]
There is an image rendering problem wrt the README in English.
A problem for another day, me thinks.

**Comment by hemangsk** [comment]
ack e656864 🎉

**Comment by hemangsk** [comment]
@rultor merge

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
