### PR TITLE
rultor: Check maintainership before merging

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by hemangsk** [comment]
ack 17797c6 b26015a 1be1591

**Comment by hemangsk** [comment]
ack 17797c6

**Comment by adtac** [comment]
@rultor merge

**Comment by hemangsk** [comment]
@rultor merge

**Comment by adtac** [comment]
@hemangsk rultor is not responding because of the github outage, probably

**Comment by hemangsk** [comment]
@rultor merge

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
