### PR TITLE
projects.html: Add difficulty row

### LINKED ISSUE #786: Add a tag and difficulty row in the project section
Adding tags and difficulty row down the mentors name row will help in providing the project overview to a great extent. 

image

### PR DESCRIPTION
**Pull request by pra17dod**
This adds Difficulty-level and Tags rows under mentors row in project section.
Closes #786

### Preview of Projects Section
Screenshot from 2021-04-04 18-06-54

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by pra17dod** [comment]
@jayvdb @abhishalya Please review the PR.

**Review by anshalshukla — COMMENTED** [review]
Please attach a screenshot with the changes.

**Comment by pra17dod** [comment]
> Please attach a screenshot with the changes.

@anshalshukla I have already attached the screenshot above.

**Review by anshalshukla — APPROVED** [review]

**Review by anshalshukla — APPROVED** [review]

**Review by CLiu13 — APPROVED** [review]
Nice job - LGTM 👍

**Comment by pra17dod** [comment]
@abhishalya Please Review the PR.

**Comment by abhishalya** [comment]
This should've failed the travis checks, because the commit shortlog is too long, and it doesn't have a full link to the issue mentioned.

Fixing this from my side for now, but please take care of this next time. Highly suggest you to go through the commit guidelines once.

**Comment by abhishalya** [comment]
Also, honestly this does not look that great. It feels like there's too much info in terms of badges. In a first glance, I suspect if everyone could interpret the meaning of those. Could be better but I guess we can pass on that for now.

**Comment by pra17dod** [comment]
> This should've failed the travis checks, because the commit shortlog is too long, and it doesn't have a full link to the issue mentioned.
> 
> Fixing this from my side for now, but please take care of this next time. Highly suggest you to go through the commit guidelines once.

Thank you. Will keep that in mind about commit messages

**Comment by pra17dod** [comment]
> Also, honestly this does not look that great. It feels like there's too much info in terms of badges. In a first glance, I suspect if everyone could interpret the meaning of those correctly. Could be better, but I guess we can pass on that for now.

Can we keep only difficulty tags? I think it will be useful.

**Review by abhishalya — APPROVED** [review]

**Comment by abhishalya** [comment]
Yeah, that might be better. Can you make that change?

>Can we keep only difficulty tags? I think it will be useful.

**Comment by pra17dod** [comment]
> Yeah, that might be better. Can you make that change?
> 
> > Can we keep only difficulty tags? I think it will be useful.

Yaa, I can. Just a moment.

**Review by abhishalya — APPROVED** [review]

**Pull request merged**
