### PR TITLE
debug_profile.md: fix spelling mistake 'desireable'

### LINKED ISSUE #280: Diff project: fix spelling mistake 'desireable'
difficulty/newcomer

Opened via [gitter](https://gitter.im/coala/coala/gsoc/?at=58dd1fcbf22385553df0ea99) by @jayvdb

### PR DESCRIPTION
**Pull request by sushilm2011**
It changes the spelling of desireable to desirable in debug_profile.md
    and improve_diff_handling.md

    Closes #280

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [1] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [1] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by rohanraju97** [comment]
I think the commit body can be something like this.

Fixes the incorrect spelling of 'desirable' in debug_profile.md
and improve_diff_handling.md

**Comment by jayvdb** [comment]
ack 6aca0bb

**Comment by jayvdb** [comment]
Needs a rebase.

**Comment by supergr35** [comment]
Uh-oh! You have have the dreaded merge commit. This is probably because you pushed the rebase(update branch from master) button in github. This is not the proper way of doing this and will break many things. Please do an interactive rebase on the commit before the merge commit and remove the merge commit line(see http://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history). See https://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing for the proper way to rebase.
(it's okay, we all make mistakes in git ;) )

**Comment by sushilm2011** [comment]
Thank You!! :) I will fix this.

**Comment by hemangsk** [comment]
@sushilm2011 , Hey feel free to ping on gitter in case of any queries :)

**Pull request closed without merging**
