### PR TITLE
materialize.css: CSS enhanced

### PR DESCRIPTION
**Pull request by fragm3**
Closes issue: https://github.com/coala/coala/issues/5861

Cursor type changes to "pointer" when hover over tabs in the header to tell quickly that it is clickable. 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by hemangsk** [comment]
@fragm3 the changes are to be done in coalaCSS repository, https://github.com/coala/coalaCSS

**Comment by fragm3** [comment]
@hemangsk should I create another pull request for it?

**Comment by hemangsk** [comment]
Yes, in the coalaCSS repo

**Comment by RaiVaibhav** [comment]
@fragm3  please rebase you commit and you did't provide the issue link in commit  message and the issue link you provided in comment is not working,if you have already move your PR  to `coalaCSS` repo then please give reference of  this PR so that we can know about it and can work accordingly

**Comment by jayvdb** [comment]
coala/coala#5861 doesnt exist.
Anyway, submitter is not active.

**Pull request closed without merging**
