### PR TITLE
Sils/projj

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by fneu** [comment]
ack https://github.com/coala/projects/commit/1ce346283d547f998691fb776df152d038c75f8goals etc. are better now.

**Comment by sils** [comment]
ack 1ce3462

**Comment by sils** [comment]
@fneu you did notice that this is now more about the core and less about writing actual metrics I guess, the project was too big IMO

**Comment by fneu** [comment]
Yes I noticed and I totally agree. It still says that multiple bears have to be included, but this way the whole project is much more defined and much more tied to coala. Choosing the metrics to implement is not a core decision of the proposal anymore which is probably a plus for a GSoC project.

Also this allows for further projectsnext year if we do our own research and properly specify which exact metrics we'd need implemented this way.

**Pull request merged**
