### PR TITLE
faq.js: Add faq

### PR DESCRIPTION
**Pull request by Shade5**
Added faq regarding start of proposal

Closes:null

### CODE REVIEW

**Comment by sils** [comment]
remove the closes line completely please ;)

**Comment by sils** [comment]
actually the whole body doesn't really add anything

**Comment by Shade5** [comment]
Body of the commit log or body of the `ans:`?

**Comment by sils** [comment]
Commit log

**Comment by sils** [comment]
ack https://github.com/coala/projects/pull/53/commits/05db682fbe07b89c758bfa93c4645a8a952dd147

**Pull request merged**
