### PR TITLE
Text Transformations.

### LINKED ISSUE #54: Use text transformations properly
http://www.w3schools.com/cssref/pr_text_text-transform.asp

### PR DESCRIPTION
**Pull request by damngamerz**
style.css: Add capitalize
Add capitalize which transforms the first letter of each word to uppercase

style.css: Add uppercase
Add uppercase transforms all characters to uppercase

style.css:Add lowercase
Add lowercase transforms all characters to lowercase

Closes #54

### CODE REVIEW

**Comment by damngamerz** [comment]
Also Tested !!
By trying on changing title "Hello there!".
using `capitalize`
screenshot from 2017-02-01 16-04-22
using `uppercase`
screenshot from 2017-02-01 16-06-06

**Comment by gkrishnan724** [comment]
ack  	d175797  19c9e2a  	a78f72c

Looks good :+1:

**Comment by supergr35** [comment]
In the future, please develop on a new branch rather than master. Here's a link to explain how :)
http://api.coala.io/en/latest/Developers/Git_Basics.html#creating-a-new-branch

**Comment by damngamerz** [comment]
@supergr35 Sure Thanks for the tip!!

**Comment by sils** [comment]
why aren't you using the transformations? Just introducing them isn't helping a lot.

**Comment by damngamerz** [comment]
@sils can you please elaborate?
what i understood is you wanted me to change existing text in .html to use those transformations!
Is that correct?

**Comment by damngamerz** [comment]
@hemangsk Need your review!! Have followed your convention(i.e.First letter as capital in texts.)
Tried to keep the website same as before and did the changes accordingly.
Here's how it looks.If anything else to be done ping me :) :+1: 
screenshot from 2017-02-03 09-29-10
screenshot from 2017-02-03 09-29-18

**Comment by hemangsk** [comment]
@damngamerz Great! that works all perfect 🎉 Rebase and it's set for merge

**Comment by damngamerz** [comment]
@hemangsk done rebase!! Thanks for your help man :+1:

**Comment by hemangsk** [comment]
ack 48e788d 3d15a34 379524c 3b4cd78 339fcf5 2b63d34 ecbd6f4

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
