### PR TITLE
Fixes #375: Center project name in modal

### LINKED ISSUE #375: Project name in modal is not perfectly centered
See [this](https://projects.coala.io/#/projects?project=improve_coala_website_%26_supporting_tools&lang=en) for clear example

Currently it's missing `padding-left`
screenshot from 2017-10-27 21-23-18

Adding `padding-left: .5em` and adjusting `padding-right: .5em` will provide a nicer look
screenshot from 2017-10-27 21-24-24

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #375 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by anshumanv** [comment]
@jayvdb I'm using spaces, still, gitmate bot is picking them as tabs, any leads?

**Comment by jayvdb** [comment]
@anshumanv , yup, it is seeing three commits and checking them all.  You need to squash your commits into one, and also update your commit message to follow http://coala.io/commit

**Comment by anshumanv** [comment]
Ah cool thanks, updating. :smile:

**Comment by jayvdb** [comment]
https://deploy-preview-486--coala-projects.netlify.com/#/projects?project=improve_lint_bear_quality looks good

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/486/commits/a4d9b76c67cef5748d47b1fea71b6c2ea7472e78

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/486/commits/228fce35ffb5851b0606bca508b95a581be9880b

**Comment by anshumanv** [comment]
Thanks! Just out of curiosity, why did you do that gitmate-bot rebase?

**Comment by jayvdb** [comment]
Because coala only uses fast forward merges.

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
You'll see it creates a nice git log, without a messy commit list full of merge commits.

**Comment by anshumanv** [comment]
Okay woah, this is cool. :smile: 

Btw sorry for keeping that issue for so long.

**Pull request merged**
