### PR TITLE
Tabs template folder to support from current directory

### PR DESCRIPTION
**Pull request by chamathpali**
Tabs template folder to support from current directory and  directory taken as a variable to be used throughout.

#137

### CODE REVIEW

**Comment by hemangsk** [comment]
Hey 😃  Please make sure to follow the commit guidelines at [coala.io/commit](https://coala.io/commit)

**Comment by yash-nisar** [comment]
PING @chamathpali Are you still on this ?

**Comment by RaiVaibhav** [comment]
@chamathpali ping, please assign yourself using using `corobo` , your commit needed rebase and also as pointed by @hemangsk  please follow commit guidelines to to improve the`Head` and `Body` of commit message

**Comment by jayvdb** [comment]
We switched to jekyll.

**Pull request closed without merging**
