### PR TITLE
faq.json: Add translation to romanian

### PR DESCRIPTION
**Pull request by Nosferatul**
Closes https://github.com/coala/projects/issues/335

### CODE REVIEW

**Comment by Nosferatul** [comment]
@jayvdb as I said that i'll translate.

**Comment by hemangsk** [comment]
@Nosferatul you would also want add the language in this array https://github.com/coala/projects/blob/master/resources/js/app.js#L5

**Comment by Nosferatul** [comment]
done

**Comment by hemangsk** [comment]
ack 319a5e9

**Comment by hemangsk** [comment]
@rultor merge!

**Comment by Nosferatul** [comment]
thx @hemangsk

**Pull request merged**
