### PR TITLE
commit-content-checks.md: New proposal

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by virresh** [comment]
I am highly interested in this project 
Another thing that we could look at could be something about the closes v/s fixes thing
We can generalise the problem of using a wrong closing keyword by integrating it with the labels api

Like generalising it apart from just type/bug, we can provide a set of labels for closes and a set of labels for fixes.
Something like suggested here : https://github.com/coala/coala/issues/5155

Does that fit in here ?
(Although probably as already suggested, if it's only for type/bug, it better fits in gitmate project)

**Comment by jayvdb** [comment]
I believe hoster issue labels is beyond the scope of this project.

However, two similar problems I was thinking about while writing this up, but didnt include due to laziness, was

1. if there are only additions in the diff, the commit message should almost certainly be 'Added ...' / same with only deletions / and modifications.

   Also the filename to be used as the prefix can be 100% deterministic based on the patch contents, with an algorithm that chooses the shortlog prefix automatically to give as much information as possible about the contents using as few characters as possible.

2. the 'threshold where a textual description is needed in the commit body'.  i.e. one liners probably dont need a text blob in the body.  two liners?  hmm.  Ideally ... that is actually based on the code complexity of the content being modified/added. ;-)

**Comment by virresh** [comment]
yeah, point 1 sounds good.
But I don't know about 2nd one.
Is it something like if the patch diff is greater than some particular length then we need significant text in the commit body ?

**Comment by kriti21** [comment]
@jayvdb This seems really cool project and the above additional points too.
 
@virresh  Could you explain the second part of point 1 above. I am slightly confused with this one. 
And regarding the 2nd point, 
>Is it something like if the patch diff is greater than some particular length then we need significant text in the commit body ? 

seems correct
 But i don't think even five liners in some cases need text blob (documentation or test related issues). This mostly depends on the code complexity. How are we supposed to judge complexity of the content being modified/added ?

**Comment by virresh** [comment]
> @virresh Could you explain the second part of point 1 above. I am slightly confused with this one.
And regarding the 2nd point,

@kriti21 , from my understanding, it is always possible to determine the shortlog prefix always, since always the prefix in the name is the file which has the maximum changes
for example if in a patch, the file PEP8Bear.py has the most changes, the shortlog prefix should be PEP8Bear ideally

**Comment by jayvdb** [comment]
Pre-requisites for this project might include merged PRs to upstream https://github.com/vcs-python/libvcs or https://github.com/vcstools

**Comment by jayvdb** [comment]
@virresh , re 2nd one, spot on.

@kriti21  Complexity can initially be simply a threshold of lines added/modified.  Worst case is someone is asked to add a commit body message when it isnt going to be very valuable above the reader seeing the code changes.  That isnt asking a lot of a contributor, so the threshold can be quite low.  A little boring and sometimes even silly, but not difficult to do.  The benefit is that then https://coala.io/commit can be very specific about what is required, which helps newcomers know what is expected of them, and a bot checks it, and soon enough we all do it instinctively because we've internalised those threshold.  But, the algorithm can improve over time, maybe next GSoC.  e.g. 'bears: Adds 100 missing docstrings' would be ample description for thousands of lines of addition, because there isnt a lot more than could be said in the commit body , and the reader is better just quickly skip through the diff to see what it is about.  That is 'hard', because then python syntax needs to be understood.  Likewise there are limitless number of specialised complexity rules which require a lot of specialised knowledge for a commit message checker.  coala can do it, but not this year ;-)

re shortlog prefix you're on the right path.  Also , there can be a priority given to certain files, and groups of files can be summarised with a directory prefix, etc, etc .  And while still being deterministic, there still could be multiple correct answers that it will accept (we have another project to allow bears to communicate multiple possible answers to the user) and only a human can choose the right one, but also the bear might strongly recommend that patch be split up into multiple commits if it cant find which part of the code changes is the primary objective of the patch.  This is a case of 90%/10% , where deterministic and correct is very easily obtainable for almost all of our PRs, and the remaining 10% are likely to be patches by senior dev members and the bot should recognise its own limitations and let us proceed even if it disagrees with our shortlog prefix.

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/489/commits/2449d0bf8a2430405ca461c312601676a1b24b54

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
