### PR TITLE
projects.js: Change difficulty label

### PR DESCRIPTION
**Pull request by dracarys09**
Change difficulty label of Aspects Support project from hard to high
to follow standard.

Fixes https://github.com/coala/projects/issues/112

### CODE REVIEW

**Comment by hemangsk** [comment]
ack e32c8b8

**Comment by sils** [comment]
rebase, or put both of your PRs into one that's way simpler

**Comment by sils** [comment]
ack https://github.com/coala/projects/pull/113/commits/8165e367dd5f9fbc89247be5bef52c03e697a772 https://github.com/coala/projects/pull/113/commits/10bfc2c4ca313737a4c0d058cb3c6b312313fe0e

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
