### PR TITLE
data/faq/application_template.md: Corrected a typo

### PR DESCRIPTION
**Pull request by lshobith**
changed from 'to you have to' to 'do you have to' in the sentence 'What parts of coala to you have to work with in order to complete this project? What else are you planning on using?'
Fixes https://github.com/coala/projects/issues/236

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by all3fox** [comment]
Hey @lshobith, you are not following http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

In particular, please switch to imperative tense:

`Corrected a typo` -> `Correct a typo`

Also, please add newlines between between the shortlog and the body, as well as the body and the commit reference.

Also, please capitalize first word in the body.

cobot mark wip

**Comment by Vamshi99** [comment]
There is no need of commit body here, also change fixes --> closes , as it doesn't fixes a real bug.

**Comment by all3fox** [comment]
@Vamshi99 but this is not a feature either, so I find your request to change `Fixes` --> `Closes` unreasonable.

However, good catch with the issue number, @lshobith please change it to coala/projects#235. The commit body could indeed be dropped or shortened too.

**Comment by hemangsk** [comment]
Hey @lshobith , minor change and we are good to go 👍 , 
In the last line of your commit message, 
It should be either, 
Fixes <url - to - issue >
or 
Closes  <url - to - issue >

Presently its just an issue url without Fixes or Closes.

**Comment by Vamshi99** [comment]
ack 20afcfc

**Comment by hemangsk** [comment]
@rultor merge

**Comment by hemangsk** [comment]
Needs rebase

**Comment by lshobith** [comment]
@hemangsk rebase completed, please try again.

**Comment by hemangsk** [comment]
ack 8398af0

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
