### PR TITLE
README.md: Replace "CODING STARTS" by "COMMUNITY BONDING"

### PR DESCRIPTION
**Pull request by arnab1896**
Issue #119 --> https://github.com/coala/projects/issues/119 should have also taken
care of README.md. Now that small change has been made which was over-looked.

Closes https://github.com/coala/projects/issues/168

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/projects/pull/169/commits/9e6119dcb58cec8d218bfa09ea8679eb4f5e8d96

**Comment by sils** [comment]
@arnab1896 can you do an amend with no changes and force push to trigger gitmate? I assume this is some github webhook problem.

**Comment by arnab1896** [comment]
@sils ; done.  :smile:

**Comment by hemangsk** [comment]
ack e9a5beb

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
