### PR TITLE
Create .coafile

### PR DESCRIPTION
**Pull request by vimcoffee**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by vimcoffee** [comment]
In this case the `.coafile` should have been empty.

**Comment by NiklasMM** [comment]
It would be great if you could add some content into the file too (and possibly fix resulting issues). An empty file does not help anyone. As pointed out [in the issue](https://github.com/coala/projects/issues/259) coala-quickstart is a great start.

If you run into issues, we're here to help!

**Comment by vimcoffee** [comment]
Alright, I will play around with the configuration file (:

**Comment by vimcoffee** [comment]
@sils @NiklasMM coala detected **a lot** of issues with the code base.

**Comment by SanketDG** [comment]
Could you show the contents of your `.coafile`? @vimcoffee

**Comment by vimcoffee** [comment]
@SanketDG @NiklasMM 
```
[default]
bears = LineCountBear, FilenameBear, InvalidLinkBear, coalaBear
files = **.js, **.md, **.css, **.html, **.yml
ignore =
max_lines_per_file = 1000

[css]
bears = CSSLintBear, SpaceConsistencyBear
files = **.css
use_spaces = True

[javascript]
bears = JSComplexityBear, JSHintBear
files = **.js

[yaml]
bears = YAMLLintBear, KeywordBear, LineLengthBear, SpaceConsistencyBear
files = **.yml
use_spaces = True
language = YAML
max_line_length = 119

[html]
bears = BootLintBear, KeywordBear, HTMLLintBear, LineLengthBear, SpaceConsistencyBear
files = **.html
use_spaces = True
language = HTML
max_line_length = 119

[markdown]
bears = MarkdownBear, KeywordBear, LineLengthBear, SpaceConsistencyBear
files = **.md
use_spaces = True
language = Markdown
```

**Comment by vimcoffee** [comment]
Generated by `coala-quickstart` and then I edited a few things.

**Comment by vimcoffee** [comment]
I got a problem.

When running `coala` the following happens:
```
[ERROR][22:42:22] There is a conflict in the version of a dependency you have installed and the requirements of coala. This may be resolved by creating a separate virtual environment for coala or running `pip install "munkres3==1.0"`. Be aware that the latter solution might break other python packages that depend on the currently installed version.
[INFO][22:42:22] Exception was:
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/coalib/coala_main.py", line 80, in run_coala
    arg_list=arg_list)

  File "/usr/local/lib/python3.5/dist-packages/coalib/settings/ConfigurationGathering.py", line 363, in gather_configuration
    log_printer)

  File "/usr/local/lib/python3.5/dist-packages/coalib/settings/SectionFilling.py", line 31, in fill_settings
    bear_dirs = section.bear_dirs()

  File "/usr/local/lib/python3.5/dist-packages/coalib/settings/Section.py", line 74, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]

  File "/usr/local/lib/python3.5/dist-packages/coalib/collecting/Collectors.py", line 303, in collect_registered_bears_dirs
    registered_package = ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2290, in load
    self.require(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2307, in require
    items = working_set.resolve(reqs, env, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.VersionConflict: (munkres3 1.0.5.5 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('munkres3==1.0'))
```


I tried to uninstall `munkres3` and install version 1.0, but the `pip3` says it cannot find this version:
```
$ pip3 install munkres3==1.0
Collecting munkres3==1.0
  Could not find a version that satisfies the requirement munkres3==1.0 (from versions: 1.0.5.5)
No matching distribution found for munkres3==1.0
```

`pip3` is already up-to-date.

Any help please?

**Comment by NiklasMM** [comment]
That's because there is no version 1.0 for that package [on PyPi](https://pypi.python.org/pypi/munkres3/1.0.5.5). Do you know where that requirement comes from?

**Comment by jayvdb** [comment]
@vimcoffee has deleted their repository.
As a result, this PR is unfixable.

**Pull request closed without merging**
