### PR TITLE
_reports: Add yzgyyang's GSoC report

### PR DESCRIPTION
**Pull request by yzgyyang**

### CODE REVIEW

**Comment by jayvdb** [comment]
Needs rebase

**Comment by yukiisbored** [comment]
ack https://github.com/coala/projects/pull/647/commits/9a7214780f9f5ed9dcd09e442a5967b8b607811f

**Comment by yukiisbored** [comment]
@gitmate-bot ff

**Comment by yukiisbored** [comment]
@jayvdb can't merge it.

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
