### PR TITLE
Update nokogiri to 1.8.2 and html-proofer to 3.8.0

### PR DESCRIPTION
**Pull request by LenaAn**
Gemfile.lock: Update nokogiri to 1.8.2 and html-proofer to 3.8.0

This updates nokogiri to 1.8.2 and html-proofer (which is dependent on 
nokogiri) to 3.8.0. This fixes GitHub warning about unsecure nokogiri
version.

Closes https://github.com/coala/projects/issues/446

### CODE REVIEW

**Comment by Makman2** [comment]
I hope those are temporary inavailabilities. Restarted the travis build. In case it passes, we have to regenerate the commit hash again so gitmate passes too (but one step after another).

Anyway, you are updating quite many dependencies, are those all implicit ones?

**Comment by LenaAn** [comment]
Most of them are dependencies of **html-proofer**. I updated **html-proofer** because the version we used to use depends on **nokogiri (~> 1.7)**

**Comment by Makman2** [comment]
Alright :)

However, some commit message fixes necessary:
1. First letter upper-case ;)
2. Please include the issue reference in the commit body
3. Optional: You could rephrase your commit message to just "Update nokogiri to ...", and explain inside the body that nokogiri is a dependency of "html-proofer" which this repository directly requires. In order to update nokogiri, html-proofer has to be updated too to version .... Maybe mentioning the reason (the security vulnerability pointed out by GitHub) doesn't harm too :)

(--> see our commit guidelines)

**Comment by LenaAn** [comment]
Please review

**Comment by hemangsk** [comment]
ack e62924b

**Pull request merged**
