### PR TITLE
editor_support.md: Remove emacs and Change coala/coala-eclipse#25

### PR DESCRIPTION
**Pull request by rahuldkjain**
coala/coala-eclipse#25 is replaced with coala/coala-eclipse#51.
coala/coala-emacs#11 is removed. emacs from the project body is also
removed.

Fixes https://github.com/coala/projects/issues/652

### CODE REVIEW

**Comment by jayvdb** [comment]
Commit message still wrong     see https://github.com/coala/projects/pull/655/commits

**Comment by rahuldkjain** [comment]
@jayvdb Commit message modified. Please review again!

**Comment by jayvdb** [comment]
commit message still wildly wrong.

See https://coala.io/commit .

**Comment by jayvdb** [comment]
Wow.

This PR now has 4 commits and 71 files are being changed.

It looks like you need to rebase it properly.  See https://coala.io/git .

**Comment by jayvdb** [comment]
ping @rahuldkjain

**Comment by jayvdb** [comment]
14 commits ; abandoned effort

**Pull request closed without merging**
