### PR TITLE
Re-label Handling Nested Languages to Difficulty: High

### LINKED ISSUE #445: Re-label Handling Nested Languages to Difficutly: High
On recent discussions with @NiklasMM on gitter we discovered that [this project](https://github.com/coala/projects/blob/master/_projects/nested_languages.md) is harder than it seems and has a lot of complications and thus it should be re-labelled to **difficulty: high**

### PR DESCRIPTION
**Pull request by tanhengyeow**
Fixes #445 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by hemangsk** [comment]
Hey @tanhengyeow , can you also add the file name in commit message as per the commit guildelines http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by tanhengyeow** [comment]
Done! Thanks for the review!

**Comment by tanhengyeow** [comment]
@hemangsk Is it ready for merging? :)

**Comment by hemangsk** [comment]
Hey @tanhengyeow  , so the commit shortlog has filename now 👍   but its longer than 50 chars which  is not in accordance with guidelines, so you gotta shorten it a bit. Also you'll have to squash the two commits into one. http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and coala.io/git have all the instructions, and feel free to ask on gitter if you are stuck :)

**Comment by tanhengyeow** [comment]
@hemangsk Done! Thanks for the help :)

**Comment by hemangsk** [comment]
@gitmate-bot rebase

**Comment by hemangsk** [comment]
ack abdca40

**Pull request merged**
