### PR TITLE
bear_updates.md: Fix typo

### PR DESCRIPTION
**Pull request by mittalshravika**
Fix typo in line 52, indetified --> identified

Closes https://github.com/coala/projects/issues/465

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
Use `Closes` instead of `Fixes`  commit message ,  and change commit message to someting like 
`Fix typo in line 52, indetified --> identified`.

**Comment by mittalshravika** [comment]
@RaiVaibhav made the changes suggested

**Comment by RaiVaibhav** [comment]
Changes not reflected here :sweat_smile:

**Comment by mittalshravika** [comment]
Sorry, but I am not able to figure out how to reflect the changes

**Comment by RaiVaibhav** [comment]
`git checkout issue465`
just use `git commit --amend`
`Enter the detail` 
`git push origin issue465 --force`

And first read what those commands does, how to use `git`

**Comment by mittalshravika** [comment]
@RaiVaibhav, I was using the above commands only for editting my commit message, but on using the command, git commit --amend, it shows a commit message other than my original.
image

**Comment by mittalshravika** [comment]
Editted my commit, I hope it shows the changes now.

**Comment by RaiVaibhav** [comment]
LGTM da5277fa1bfb4b3f8deadb760c4bb492bb2ea11f

**Comment by hemangsk** [comment]
ack da5277f

**Pull request merged**
