### PR TITLE
app.js: Remove unused filter filter_desc

### LINKED ISSUE #144: Markdown not rendering properly in project's short description in cards
We're now using "desc" field for a one/two line summary of the project, therefore filter (filter_desc) is not required on description. This filter splits the sentence on first full stop, which is corrupting the markdown.

### PR DESCRIPTION
**Pull request by hemangsk**
Markdown rendering correctly in Project Description

Fixes #144
screen shot 2017-01-26 at 8 29 56 pm

### CODE REVIEW

**Comment by sils** [comment]
@hemangsk please do an amend with no changes and a force push to trigger github

**Comment by sils** [comment]
ack https://github.com/coala/projects/pull/146/commits/cf3b7fc9f7329e7d7115c0dc72f1057d20bb9393 https://github.com/coala/projects/pull/146/commits/f8934ccab6a23aba23a9688ac63b63a1f64061aa  https://github.com/coala/projects/pull/146/commits/a3b020b50964ab36e7f64a3db6710dd5058d136d

**Comment by hemangsk** [comment]
reack 43d15dd d2b8dae c91337c

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
