### PR TITLE
_projects: Fix trailing whitespace in YAML

### PR DESCRIPTION
**Pull request by neelanshsahai**
Removed the trailing whitespaces from the
YAML front matter block of the Markdown files.

Fixes https://github.com/coala/projects/issues/386

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by neelanshsahai** [comment]
@IpshitaC actually I copied it from https://github.com/coala/projects/pull/387
But if you suggest, I will make the changes :smile:

**Comment by neelanshsahai** [comment]
@IpshitaC done :+1:
please have a look

**Comment by yashovardhanagrawal** [comment]
deploy is failing

**Comment by yashovardhanagrawal** [comment]
unack https://github.com/coala/projects/pull/404/commits/5b460b8e69b3d1e1492909839faa9bcd8de74d7b

**Comment by neelanshsahai** [comment]
The deploy is failing because of the failure of gem installation during the build. I don't know that whether there are any faults in my PR or not but while exploring a bit I found this https://github.com/gatsbyjs/gatsby/issues/2441

**Comment by jayvdb** [comment]
You need to rebase.

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/404/commits/0c2f8a0ff4bf4781ed70162293c0274345eb33e5

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
