### PR TITLE
Fixed language drop-down menu position.

### LINKED ISSUE #363: Misplaced drop-down for switching languages?
The drop down seems to have absolute/fixed to lower left corner, but it overlaps with the project cards, hence isn't clickable
Opened by @meetmangukiya at [gitter/coala/coala/offtopic](https://gitter.im/coala/coala/offtopic?at=59a8429619147ac32316343b)

### PR DESCRIPTION
**Pull request by aashutoshrathi**
Fix language drop-down menu spacing issues.

Closes #363

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mohitkyadav** [comment]
@aashutoshrathi Please follow http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html
```
fileName: Mention changes summary
Changes

Closes #{issue number}
```

**Comment by prnvdixit** [comment]
@aashutoshrathi Please, can you share some screenshots as to how the page looks like now on mobile devices and desktop (and that spacing issue is resolved 😄)? 👍

**Comment by aashutoshrathi** [comment]
Desktop look:
image

**Comment by prnvdixit** [comment]
Umm... The Shortlog is still not in imperative mood. Actually, you changed the title of your PR 😄.
Ideally, Shortlog should be ```index.html: Fix spacing issues``` as drop-down issue has been solved in another PR already 😃. You can amend your Shortlog by ```git commit -a --amend``` 👍.
Also, the spacing issue seems to be fixed now - Good work 👍

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
