### PR TITLE
Mentors list

### PR DESCRIPTION
**Pull request by chttrjeankr**
Fixes: #777 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by chttrjeankr** [comment]
On running coala locally with HTMLLintBear on the only HTML file modified in this PR (`partials/tabs/mentors.html`), I get the following log.
image
image
These lines weren't modified in this PR.
@abhishalya, would like your views on the logs.

**Comment by abhishalya** [comment]
Hmm, weird, can you fix it here.

**Comment by chttrjeankr** [comment]
Created an empty HEAD commit with a shortlog of under 50 characters. :)

**Comment by chttrjeankr** [comment]
Hey @abhishalya, this PR is ready to review and merge. Let me know if there's any scope for improvement.

**Comment by abhishalya** [comment]
@chttrjeankr Sorry for the delay, I was inactive for some time. Thanks for the PR, it looks good. :)

Just one small change I think we can do is maybe we should remove the `completed` tag since if we had new mentors and new gsoc then they won't show up here (since the projects weren't completed). Although, we'd like to have them list on the mentors page.

Can you make this change, I'll merge it. Also, I'm updating mentors list on https://github.com/coala/projects/pull/782 so you might've to rebase this first.

**Comment by chttrjeankr** [comment]
> we should remove the `completed` tag

I believe a better option would be to change the filter used to display mentors. Rather than just choosing `completed` we can also choose `in progress` tags and display all such mentors.

If you meant removing the tag completely from the filter, it'll display mentors from `disabled` projects as well.

@abhishalya I'll rebase and push my changes by EOD.

**Comment by abhishalya** [comment]
The thing is earlier we used to constantly participate in gsoc and we used to have new project ideas all the time. Now its slightly changed and I want the mentors to be listed as per the last gsoc we had. If its ongoing then let the list display them. I don't think we had any disabled project last year but I don't think it would've been a problem to show the mentors even if we had one.

**Comment by chttrjeankr** [comment]
@abhishalya Rebased and made the desired changes. Open for review. :rocket:

**Comment by abhishalya** [comment]
Looks good, one final step. Squash these commits into one

**Comment by abhishalya** [comment]
Merged! Thanks for the contribution :)

**Pull request merged**
