### PR TITLE
debug_profile.md: Fix typo

### PR DESCRIPTION
**Pull request by vimcoffee**
Correct typo in word "documentation"

Closes https://github.com/coala/projects/issues/253

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by supergr35** [comment]
Please change "Fixes" to "Closes" in your commit message. Check our documentation

**Comment by vimcoffee** [comment]
@supergr35 I checked it before commiting ^^ The [issue](https://github.com/coala/projects/issues/253) was labeled as *bug* so I wrote *Fixes*.

I will change (:

**Comment by yashtrivedi96** [comment]
Seems good:)

**Comment by hemangsk** [comment]
ack 0434156

**Comment by vimcoffee** [comment]
@hemangsk what do you mean by that?

**Comment by hemangsk** [comment]
@vimcoffee Check this out http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing. To sync your changes with this remote repository you need to rebase. This guide will explain about rebase in sufficient detail. Please feel free to ask on gitter incase of any query 😃

**Comment by vimcoffee** [comment]
@hemangsk thanks, I've been tinkering with this for the last 20 minutes :D

**Comment by hemangsk** [comment]
ack 06f4f28

**Comment by vimcoffee** [comment]
@hemangsk rebased :D

**Pull request merged**
