### PR TITLE
data/projects/*.md: Replace "CODING STARTS" with "COMMUNITY BONDING"

### PR DESCRIPTION
**Pull request by arnab1896**
This clarifies the end of community bonding

Fixes https://github.com/coala/projects/issues/119

### CODE REVIEW

**Comment by hemangsk** [comment]
The second "this" in commit body is not required I think, makes the sentence a bit confusing. Just 'This clarifies the end of community bonding ' ?

**Comment by sims1253** [comment]
you might want to take a look at coala.io/commits for help on how to write commit messages.

**Comment by arnab1896** [comment]
@hemangsk @Nosferatul @sims1253 ; thanks for your valuable feedback.
I have updated the description. Is it correct now? Or is there any scope for improvement?

**Comment by sims1253** [comment]
You have to change your commit message from the `Fixes` to a `Closes` as this i not a bugfix.
you can do it with the following commands:

`git commit --amend` This lets you change the commit message of your last commit

`git push -f` This forces a push, overriding the old commit in the online repository with the new one

**Comment by arnab1896** [comment]
@sims1253 , @Nosferatul , @hemangsk , is it correct now?

**Comment by Warewolf96** [comment]
ack https://github.com/coala/projects/pull/152/commits/294e314a6f277e35af6a55a69ff46962a1d0ad4c

**Comment by sims1253** [comment]
you have to rebase. The newcomer guide should hold a step by step guide for that. if any problems occur just ask here or in the [gitter channel](coala.io/chat)

After rebasing please check if if any new projects were added and fix them too if needed :)
Nice work!

**Comment by arnab1896** [comment]
OOPS! another project was added. Wait, let me modify that too!

**Comment by arnab1896** [comment]
DONE!

**Comment by sims1253** [comment]
you didn't push the changes for the new project

**Comment by arnab1896** [comment]
@sims1253 , Do I have to follow this?
step 1 : Commit changes for the remaining two projects.
step 2 : squash the above 2 commits?
Am i correct?

**Comment by sims1253** [comment]
unack 4cebfe870f5723bf497e2bfc75016aea8760b254

**Comment by sims1253** [comment]
@arnab1896 yes that sounds correct.

**Comment by sims1253** [comment]
@damngamerz please be more careful when ack-ing PRs. You are essentially saying it is in a mergable state and taking responsibility for that. As long as you are not a maintainer this doesn't matter as much as only we merge and thus have to recheck anyway but when in doubt, just don't give an ack and keep reviewing :)

**Comment by damngamerz** [comment]
@sims1253 Will keep that in mind! Thanks :)

**Pull request closed without merging**
