### PR TITLE
.editorconfig: Add new file

### PR DESCRIPTION
**Pull request by ananyaarun**
Closes https://github.com/coala/projects/issues/388

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by ananyaarun** [comment]
@jayvdb , I have added the .editorconfig file in the main project directory .... not sure where the Travis tests have failed.

**Comment by Man-Jain** [comment]
Were you assigned to the issue? Cause I couldn't see it. And if not you should not work one the issue. Also this issue is very old maybe it isn't even needed now. So please get assigned first.

**Comment by ananyaarun** [comment]
@Man-Jain can it be assigned to me now if possible ?

**Comment by Man-Jain** [comment]
@yes why not. Just ask it in the coala channel. And then people will guide you further.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by ananyaarun** [comment]
@jayvdb can this PR be reviewed ? So that it can be merged ?

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/661/commits/329f2e80a841a15116217e6bfc230e5acc2e922c

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
