### PR TITLE
Hemangsk/flagsort

### PR DESCRIPTION
**Pull request by hemangsk**
1 ) When we click on the in-progress flag
screencapture-localhost-8080-1493018848033

2) When we click on the high involvement flag
screencapture-localhost-8080-1493018860941

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by gkrishnan724** [comment]
@hemangsk works good locally!

but why do we have the status for high-involvement as 'crowded'?  why don't we keep it as high_involvement? because if people search for high-involvement projects, they will probably input high-involvement in the search bar not crowded I guess.

**Comment by sims1253** [comment]
can we support multiple statuses on one project? Right now we don't need it but might in the future.

**Comment by hemangsk** [comment]
Yep, on it 🚀

**Comment by hemangsk** [comment]
We are now using Jekyll and searching "High Involvement" or "In Progress" brings the correct results :) 
For https://github.com/coala/projects/pull/285#issuecomment-297673632 we have a new issue on https://github.com/coala/projects/issues/470

**Pull request closed without merging**
