### PR TITLE
Update debug_profile.md file

### PR DESCRIPTION
**Pull request by patilpushkarp**
docuemntation is changed to documentation: Fix typo #253

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Vamshi99** [comment]
@patilpushkarp please follow commit guidelines at http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html and edit the commit by using "git commit -a --amend"

**Comment by hemangsk** [comment]
Hey @patilpushkarp, Please resolve the issues pointed out by reviewers.
Marking WIP

**Comment by patilpushkarp** [comment]
Please tell me the detailed procedure to do this task. This is my first repo. I read the guidelines provided above but I don't know how to go the debug_profile.md file.

**Comment by vimcoffee** [comment]
Hello @patilpushkarp.

First of all, you should have executed the `cobot assign <issue_link>` on [coala gitter](https://gitter.im/coala/coala) to get assigned to the issue.
This is described in [Picking Up an Issue](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-3-picking-up-an-issue) section.

As it was already pointed by @Vamshi99, you should read carefully [this reference](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#how-to-write-good-commit-messages) once again and fix the mistakes by running `git commit -a --amend`.

Here's a list of things I would correct in your commit message if I were you:
 * Shortlog
 * Commit body
 * Issue reference

**Comment by vimcoffee** [comment]
@patilpushkarp please read carefully the [Newcomers Guide](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html) and make sure you go through all the steps described on the page.

**Comment by jayvdb** [comment]
Already fixed in https://github.com/coala/projects/pull/254

**Pull request closed without merging**
