### PR TITLE
fixed_typo

### PR DESCRIPTION
**Pull request by raj-maurya**
Hi,

Please review the pull request .
Fixes: https://github.com/coala/projects/issues/208

Thank You

### CODE REVIEW

**Comment by arnab1896** [comment]
@raj-maurya ; need any help with editing your commit message? Do let me know.

meanwhile; carefully read this if you still haven't-----> http://api.coala.io/en/latest/Developers/Git_Basics.html

**Comment by dracarys09** [comment]
@raj-maurya the deadline is in 17 hours... can you address this issues like ASAP...

**Comment by raj-maurya** [comment]
@dracarys09 

amend for commit message is done!

and what it means [deadline is in 17 hours ?]

Thanks

**Comment by dracarys09** [comment]
@raj-maurya by deadline I meant deadline for application of organizations for GSoC 2017...

read about how to squash commits... you need to squash them... changes looks good...
squash your commits and we are good to go...

**Comment by sims1253** [comment]
there is coala.io/rebase to help you with it

**Comment by yash-nisar** [comment]
PING @raj-maurya

**Comment by raj-maurya** [comment]
Please review!

I have squashed the commits, Thanks!

**Comment by hemangsk** [comment]
@raj-maurya can you just make sure the commit shortlog description is in imperative present form (Fixed -> Fix)[coala.io/commit](http://coala.io/commit), otherwise perfect

**Comment by raj-maurya** [comment]
@hemangsk @yash-nisar 

Please review the changes!

**Comment by hemangsk** [comment]
ack bffb503

**Comment by hemangsk** [comment]
@rultor merge

**Comment by yash-nisar** [comment]
One last step and we're good to merge. `Fixes` should only be used when your commit fixes a bug. Since your commit does not fix a bug, please use `Closes` instead of `Fixes`.

**Comment by yash-nisar** [comment]
@hemangsk The commit guidelines have not been followed. :O

**Comment by yash-nisar** [comment]
unack bffb503037dba8a732d1e169f7db7515d814871f

**Comment by hemangsk** [comment]
Sorry, but why should ```Closes``` be used, this doesn't add a new feature or enhancement. This literally 'Fixes' a typo.

**Comment by hemangsk** [comment]
@raj-maurya can you give it a rebase 😃 . Have a look here in case you're looking for help with rebase [coala.io/rebase](http://coala.io/rebase) 🚀   And you can also discuss on the gitter channel if you are stuck anywhere 👍

**Comment by RohanVB** [comment]
tbh I dont think we needed an issue in this repo, it could just be the shortlog.

**Comment by yash-nisar** [comment]
@hemangsk , As mentioned in the docs,
> If a specific issue may lead to an unintended behaviour from the user or from the program it should be considered a bug, and should be addresed with Fixes.

This commit merely fixes a typo which shouldn't be considered as a bug IMO.

**Comment by yash-nisar** [comment]
Alright, we can get this closed since we are short of time. :)

**Comment by yash-nisar** [comment]
ack bffb503037dba8a732d1e169f7db7515d814871f

**Comment by meetmangukiya** [comment]
@rultor merge!

**Comment by meetmangukiya** [comment]
Needs a rebase

**Comment by sims1253** [comment]
ack eff7f9c7a3202a929863e05cff4267b27306dc7f @raj-maurya

**Comment by raj-maurya** [comment]
Thank you, everyone :)

**Pull request merged**
