### PR TITLE
style.css: Fix style issues

### PR DESCRIPTION
**Pull request by hemangsk**
-  Improves styling in card
screen shot 2017-01-18 at 3 58 37 pm

- Eliminates excessive uppercasing
screen shot 2017-01-18 at 3 57 13 pm

### CODE REVIEW

**Comment by jayvdb** [comment]
ack 47fa0a5 6279f77 014100a

**Comment by sils** [comment]
maybe squash last two commits?

**Comment by hemangsk** [comment]
ya squashing the last two

**Comment by sils** [comment]
reack https://github.com/coala/projects/pull/66/commits/9478b95a75ee9e0e8f303fe5ee20a2bb325e1d74 https://github.com/coala/projects/pull/66/commits/56ec48dae9ef801acc3cc7a456d67c50fe41f605 https://github.com/coala/projects/pull/66/commits/66cada83a88e612e7bb8e40f51efda4a654bb423

**Comment by sils** [comment]
ack https://github.com/coala/projects/pull/66/commits/e39b265550dd2b6821bdc5920ce89a8950f61eb4

**Pull request merged**
