### PR TITLE
use_coala.md: Fix typo

### PR DESCRIPTION
**Pull request by yashovardhanagrawal**
Fixes typo of met to meet in
_projects/use_coala.md

Closes: https://github.com/coala/projects/issues/419

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by newbazz** [comment]
ack ef49c993f8b281092f78403a49d4b443c

**Comment by prnvdixit** [comment]
Umm... @yashovardhanagrawal I think you already have one PR in queue (the GIF one?).... Please, try not to solve more newcomer issues 😉 👍

**Comment by prnvdixit** [comment]
unack ef49c993f8b281092f78403a49d4b443cb9e12d4

**Comment by yashovardhanagrawal** [comment]
I have done the suggested changes

**Comment by yashovardhanagrawal** [comment]
@prnvdixit I did this as the process was blocked for that GIF PR

will not do any newcomer PR now

**Comment by prnvdixit** [comment]
Also, please refrain from pushing commits from your "master" branch.

**Comment by prnvdixit** [comment]
ack 94b4194d592b85c09112af57b897b23ca21e9a52

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
