### PR TITLE
Jekyll Troubleshoot link added in README

### PR DESCRIPTION
**Pull request by Bhola-B2C**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Bhola-B2C** [comment]
Reference Issue: https://github.com/coala/projects/issues/457

**Comment by monsij** [comment]
@Bhola-B2C  I think the issue is not yet assigned to you

**Comment by Bhola-B2C** [comment]
@monsij but I've already started to work on this issue :)

**Comment by monsij** [comment]
@Bhola-B2C  : Kindly go through http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#welcome-to-the-newcomers-guide

**Comment by Bhola-B2C** [comment]
@virresh plz check the PR

**Comment by virresh** [comment]
@Bhola-B2C , as @monsij  rightly said, it is best to get assigned to an issue first before sending a pull request. It really helps to ensure no one's work goes waste. So probably you can wait for a while till a maintainer assigns you this issue and in the meanwhile contribute by solving other issues / reviewing PR's :).

**Comment by Bhola-B2C** [comment]
Okay

**Comment by Bhola-B2C** [comment]
@monsij Ididn't get you.

**Comment by Bhola-B2C** [comment]
@virresh Please review this. Changes done!!

**Comment by Bhola-B2C** [comment]
In commit body you mean ??

**Comment by virresh** [comment]
Yes @Bhola-B2C 
Just replace the whitespaces with Closes.
Have a look at the commit samples, it will become clearer :sweat_smile:

**Comment by Bhola-B2C** [comment]
@virresh Now check 
image

**Comment by Bhola-B2C** [comment]
@monsij please review this.

**Comment by hemangsk** [comment]
ack bbc9a03

**Pull request merged**
