### PR TITLE
Change blog URL for RJ722

### PR DESCRIPTION
**Pull request by RJ722**

### CODE REVIEW

**Comment by RJ722** [comment]
Strange!

**Comment by RJ722** [comment]
> Why a trailing period in shortlog?

Oops, that is a mistake. Thanks for pointing it out @ksdme! :-)

**Comment by jayvdb** [comment]
ack https://github.com/coala/projects/pull/572/commits/5563ef8b449d1f77453c446bbc5f0bb652002538

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
