### PR TITLE
add_repo_license.md : Replaced spaces with _ in template

### LINKED ISSUE #383: Replace space with _ in Step 3 URL of license task
The spaces in `<your username>/<repository name>` make the rendered version appear strange.
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/gci?at=59f71dce97cedeb0482b45ae)

### PR DESCRIPTION
**Pull request by anshumanv**
Replaced spaces with _ in the template used in STEP 3 URL used to create license task.

Fixes #383 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by anshumanv** [comment]
@Monal5031 please see if things are in place. :+1:

**Comment by prnvdixit** [comment]
Ohh.... Sorry - It already got approved while I was reviewing 😅

**Comment by anshumanv** [comment]
Thanks for the review @Monal5031 @prnvdixit :+1:

**Comment by Monal5031** [comment]
ack 9941119

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
