### PR TITLE
_faq/application-template.md: Make GSoC application template dynamic

### PR DESCRIPTION
**Pull request by samuelpiltch**
Have the year on the GSoC application template on the FAQ page change based on the current year.

Closes https://github.com/coala/projects/issues/671

### CODE REVIEW

**Comment by srivama** [comment]
The changes are fine :+1: Just rebase and amend your commit message (There's some `...` in it and you can exclude `_faq` before the filename), and your'e ready to hop to your new issue :wink:

**Comment by samuelpiltch** [comment]
Just realized this implementation is flawed.
@srivama Do you happen to know when the student application period is? I'm not familiar with GSoC but a google search got me March 12 - 27, 2018. Is this period between the same dates every year?

**Comment by srivama** [comment]
Oh wait! Yes, I noticed that.

**Comment by srivama** [comment]
It's from May to August.

**Comment by samuelpiltch** [comment]
Changing it to the current year since application period for 2019 projects are between May-Aug 2019.

**Comment by srivama** [comment]
That wont be correct either, it should point to next year Sept onwards.

**Pull request closed without merging**
