### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by NickBellamy**
Fixes https://github.com/coala/projects/issues/379

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by NickBellamy** [comment]
Hi prakashdanish, I've read the commit guide, but I can't work out how my commit doesn't comply with the guidelines.  Could you kindly clarify how it should be formatted please?  Sorry if this is a silly question, I'm new to contributing to other projects, and I appreciate your patience!

**Comment by PlentyMore** [comment]
>A commit message consists of 3 
>- shortlog
>- commit body
>- issue reference

>Example:

>setup.py: Change bears' entrypoint

>This entrypoint ensures that coala discovers the bears correctly.
>It helps not writing more functions inside ``coalib`` for this.

>Closes https://github.com/coala/coala/issues/5861
 
so, you shoud add the commit body :)

**Comment by NickBellamy** [comment]
I've updated the commit now, so it should be good to go.  Thanks again for the patience, I'm still getting used to this.  I did indeed read the standard guidelines, but I got a little confused because the second bullet point under the "Commit Body" heading specifically says "Not mandatory".  Hopefully this is ok now though, and if there are any other problems then please let me know.

**Comment by Makman2** [comment]
In this case I would also say that a body is not really necessary. Fixing a typo is understandable from the shortlog ;)
However, please add the filename as a tag to the shortlog: `add_repo_license.md: Fix typo`

**Comment by Makman2** [comment]
I've just seen that you weren't assigned to the issue. Please follow our newcomer guide next time and get assigned first before you start working.

**Comment by hemangsk** [comment]
ack 14cbaa0

**Comment by hemangsk** [comment]
@rultor merge

**Pull request merged**
