### PR TITLE
Added new entry in FAQ

### PR DESCRIPTION
**Pull request by amitsin6h**
Added new entry in FAQ regarding gsoc application.

Good to close https://github.com/coala/projects/issues/424

### CODE REVIEW

**Comment by IpshitaC** [comment]
As @prashant0598 suggested, please squash all your commits into a single commit.
Marking this wip.

**Comment by yashovardhanagrawal** [comment]
Also first get the issue assigned to yourself via corobo in gitter chat using

`corobo assign <issue link>'

follow the commit guidelines
I have mentioned an example in your other PR

**Comment by Makman2** [comment]
Duplicate of https://github.com/coala/projects/pull/425, closing. Please submit your changes there.

**Comment by yashovardhanagrawal** [comment]
@Makman2 I feel it's not a duplicate, he has addressed two different issues in these two PRs

just the thing is he has added extra commit related to that PR also

**Comment by jayvdb** [comment]
Please only have one FAQ entry in this PR.

**Comment by amitsin6h** [comment]
closing this PR due to https://github.com/coala/projects/pull/425 .Which solves the issue

**Pull request closed without merging**
