### PR TITLE
automate_dependacy_repology.md: Add mentor underyx

### PR DESCRIPTION
**Pull request by jayvdb**
Also removes mentor xferra, who was moved to
the newer BSD specific repology project.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Looks good, wasn't @margobra8 (Marcos Gómez) Also one of the mentors? We can add him here in the same PR/Commit, else I will make a new one.

**Comment by jayvdb** [comment]
reack https://github.com/coala/projects/pull/584/commits/52217bce0856f4910c6a8a315840c2e0a8e2c93d

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@nemaniarjun @margobra8 , we are not listed the extra mentors on the project pages, especially not if they are actually very active helping.

**Pull request merged**
