### PR TITLE
lots of stuff by now

### PR DESCRIPTION
**Pull request by sils**
Closes https://github.com/coala/projects/issues/12

### CODE REVIEW

**Comment by jayvdb** [comment]
So the title of this PR is a bit misleading ... ;-)

**Comment by sims1253** [comment]
ack f66e3c0a549ae38cc9ce9d01bf5852f2656604e2

**Comment by hemangsk** [comment]
ack 108e5a3

**Comment by hemangsk** [comment]
ack 3b67729

**Comment by hemangsk** [comment]
ack 108e5a3

**Comment by hemangsk** [comment]
ack 97a507b

**Pull request merged**
